; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600 
board_build.filesystem = littlefs

build_flags = 		
	; -DDEBUG_ESP_PORT=Serial
	; -DCORE_DEBUG_LEVEL=5		
	-Wl,--print-memory-usage
    -Iinclude
    -Isrc/tasks
    -Isrc/hal
    -Isrc/services
	-Isrc/utils


lib_deps = 
	esp32async/AsyncTCP @ ^3.4.5
	mathieucarbou/ESPAsyncWebServer@^3.6.0
	links2004/WebSockets@^2.4.1
	256dpi/MQTT@^2.5.2
    https://github.com/ayushsharma82/AsyncElegantOTA.git
	arduino-libraries/NTPClient@^3.2.1
	bblanchon/ArduinoJson@^7.4.2
	mikaeltulldahl/AsyncOta@^1.0.2
	vshymanskyy/StreamDebugger@^1.0.1
	4-20ma/ModbusMaster@^2.0.1